language: ruby
cache: bundler
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
branches:
  only:
  - gh-pages
before_install:
- gem install bundler -v 2.0.2
script:
- bundle exec jekyll build
deploy:
  provider: pages
  local-dir: _site
  target-branch: master
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: gh-pages
